language: node_js

node_js:
  - 8
  - 6

script:
  - npm run build

jobs:
  include:
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm release

after_failure:
  - cat /home/travis/.npm/_logs/*