language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: "10"
      after_script:
        - cat /home/travis/.npm/_logs/*
      script:
        - npm run version
      on:
        tags: true
      skip_cleanup: true

after_failure:
  - cat /home/travis/.npm/_logs/*