language: node_js
node_js:
  - "8"
  - "7"
cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run build

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: "8"
      if: branch = master
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        api_key: $NPM_TOKEN
        email: $NPM_EMAIL
        skip_cleanup: true
        script:
          - npm run release

after_failure:
  - cat /home/travis/.npm/_logs/*