language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run version
      on:
        tags: true
      skip_cleanup: true

after_failure:
  - cat /home/travis/.npm/_logs/*