language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run build

jobs:
  include:
    - stage: release
      node_js: 9
      script:
        - npm run release
      if: branch = master
      skip_cleanup: true

after_failure:
  - cat /home/travis/.npm/_logs/*